---

- name: "configuration play." 
  hosts: backend
  user: ubuntu
  become: yes
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # pre_tasks:
  #   - name: "wait 600 seconds for target connection to become reachable/usable."
  #   - raw: sleep 600

  #   - name: "install python for Ansible."
  #   - raw: sudo apt-get -y install python-minimal
  #     register: py_minimal_output

  roles:
    - configure-server
