- name: "Install Deps"
  become: yes
  shell: |
      apt-get update
      apt-get -y install build-essential
      apt-get -y install curl openssl libssl-dev
      git clone https://github.com/joyent/node.git
      cd node
      git checkout v0.10.24
      ./configure
      make
      sudo make install
#    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
#    sudo apt -y upgrade
#    sudo apt install -y nodejs

# - name: "Install PM2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

- name: "Install PM2 via shell"
  become: yes
  shell: |
      npm install pm2 -g

- name: Makedir
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy build"
  unarchive:
    src: /tmp/backend/backend.tar.gz
    dest: /home/ubuntu/backend/

# - name: "Copy package.json"
#   copy:
#     src: /tmp/saveme/package.json
#     dest: /home/ubuntu/backend/

- name: "NPM Install"
  shell: |
    cd /home/ubuntu/backend    
    npm install 